[package]
name = "verix-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pc-hal-util = { path = "../pc-hal-util" }
pc-hal = { path = "../pc-hal" }
