[package]
name = "ox_rcalc-client"
version = "0.1.0"
authors = ["Sebastian Humenda <shumenda@gmx.de>"]
edition = "2021"

[dependencies]
l4 = { path = "../../../l4rust/l4-rust/" }
l4_derive = { path = "../../../l4rust/l4_derive-rust/" }
l4re = { path = "../../../l4rust/l4re-rust/" }
